[package]
name = "apex-frontend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
apex-shared = { path = "../shared" }
chrono = { workspace = true }
console_error_panic_hook = "0.1.7"
leptos = { version = "0.6", features = ["csr"] }
leptos_meta = "0.6"
leptos_router = { version = "0.6", features = ["csr"] }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
urlencoding = "2"
wasm-bindgen = "0.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
gloo-net = "0.6"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["RequestCredentials", "Window", "Location", "Storage", "WebSocket", "MessageEvent", "MediaQueryList"] }

[dev-dependencies]
tokio = { workspace = true }
[lints]
workspace = true
