//! LLM-powered recipe hypothesis generation.
//!
//! The recipe engine uses hand-crafted signal recipes (JSON/TOML) to detect
//! intelligence patterns.  This module uses the LLM to:
//! - **Generate new recipe candidates** from observed data patterns
//! - **Improve existing recipes** based on false-positive analysis
//! - **Discover cross-domain signal combinations** missed by human analysts
//! - **Evaluate recipe quality** against historical outcome data
//!
//! Generated recipes are returned in the structured `RecipeCandidate` format
//! which can be persisted directly to the recipe staging table.

use crate::inference::{ChatMessage, InferenceConfig, LlmClient};
use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

// ─────────────────────────────────────────────────────────────────────────────
// Output types
// ─────────────────────────────────────────────────────────────────────────────

/// A signal specification inside a candidate recipe.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CandidateSignalSpec {
    pub observation_type: String,
    pub field: String,
    pub operator: String,
    pub threshold: Option<f64>,
}

/// A transform specification inside a candidate recipe.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CandidateTransformSpec {
    pub field: String,
    pub transform_type: String,
}

/// A candidate recipe generated by the LLM.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecipeCandidate {
    /// Unique code for this recipe (e.g. "EMS_EXPANSION_DUAL_SRC")
    pub code: String,
    /// Human-readable name
    pub name: String,
    /// Full description of what this recipe detects
    pub description: String,
    /// Risk category: supply_chain | geopolitical | competitive | regulatory | financial | technology | personnel
    pub category: String,
    /// Severity: critical | warning | info
    pub severity: String,
    /// Targeted region codes (e.g. ["TN", "MA", "CN"])
    pub regions: Vec<String>,
    /// Constituent signal specs
    pub signals: Vec<CandidateSignalSpec>,
    /// Confidence threshold for firing
    pub confidence_threshold: f64,
    /// Narrative template with {entity} and {signal} placeholders
    pub narrative_template: String,
    /// Action template
    pub action_template: String,
    /// LLM's reasoning for why this recipe would be valuable
    pub hypothesis_rationale: String,
    /// Estimated base rate of this signal (per-company per-week)
    pub estimated_base_rate: f64,
    /// Expected precision upon production deployment
    pub expected_precision: f64,
}

/// Result of recipe quality evaluation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecipeEvaluation {
    /// Recipe code being evaluated
    pub recipe_code: String,
    /// Assessment: keep | improve | deprecate | replace
    pub verdict: String,
    /// Observed issues
    pub issues: Vec<String>,
    /// Suggested improvements to signals
    pub signal_improvements: Vec<String>,
    /// Suggested threshold adjustments
    pub threshold_adjustments: HashMap<String, f64>,
    /// Updated narrative template if improvement is suggested
    pub improved_narrative: Option<String>,
    /// Confidence in this evaluation
    pub confidence: f64,
    /// Reasoning for verdict
    pub reasoning: String,
}

/// Batch of recipe improvement suggestions from false-positive analysis.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecipeImprovementBatch {
    /// Recipe code
    pub recipe_code: String,
    /// Current false positive rate
    pub current_fpr: f64,
    /// Root cause of false positives
    pub fp_root_cause: String,
    /// Signal to add to filter false positives
    pub additional_filter_signals: Vec<CandidateSignalSpec>,
    /// Threshold adjustments to reduce false positives
    pub threshold_tightening: HashMap<String, f64>,
    /// Estimated new false positive rate after adjustments
    pub projected_fpr: f64,
    /// Confidence in projections
    pub confidence: f64,
}

// ─────────────────────────────────────────────────────────────────────────────
// Hypothesis generator
// ─────────────────────────────────────────────────────────────────────────────

/// LLM-powered recipe hypothesis generator.
pub struct RecipeHypothesisGenerator {
    client: LlmClient,
}

impl RecipeHypothesisGenerator {
    pub fn new(client: LlmClient) -> Self {
        Self { client }
    }

    /// Generate new recipe candidates from a pattern description.
    ///
    /// `pattern_description` — observed data pattern (e.g. "companies in TN showing
    ///   simultaneous hiring surge + new facility signals precede expansion announcements")
    /// `available_signal_types` — list of observation types available in the system
    /// `n_candidates` — how many recipes to generate (1..=5)
    pub async fn generate_recipe_candidates(
        &self,
        pattern_description: &str,
        available_signal_types: &[String],
        n_candidates: usize,
    ) -> Result<Vec<RecipeCandidate>> {
        let n = n_candidates.clamp(1, 5);
        let signal_types_text = available_signal_types.join(", ");

        let system = concat!(
            "You are an expert at designing signal detection recipes for an OSINT intelligence platform ",
            "covering the electronics and defense manufacturing sector. You design precise, low-false-positive ",
            "recipes that detect meaningful business intelligence signals.\n/no_think"
        );

        let user = format!(
            r#"Design {n} recipe candidate(s) to detect the following pattern:

PATTERN: {pattern_description}

AVAILABLE SIGNAL TYPES: {signal_types_text}

For each recipe, respond with a JSON array of recipe objects:
[
  {{
    "code": "<SCREAMING_SNAKE_CASE unique code>",
    "name": "<Human readable name>",
    "description": "<Full description of what this detects>",
    "category": "<supply_chain|geopolitical|competitive|regulatory|financial|technology|personnel>",
    "severity": "<critical|warning|info>",
    "regions": ["<region codes>"],
    "signals": [
      {{
        "observation_type": "<from available types>",
        "field": "<field name>",
        "operator": "<increase|decrease|above|below|equals>",
        "threshold": <number or null>
      }}
    ],
    "confidence_threshold": <0.5-0.95>,
    "narrative_template": "{{entity}} shows {{signal}} — implication...",
    "action_template": "Review {{entity}} positioning in {{region}}",
    "hypothesis_rationale": "<why this recipe would be valuable>",
    "estimated_base_rate": <0.001-0.1>,
    "expected_precision": <0.6-0.95>
  }}
]

Respond ONLY with the JSON array."#,
            n = n,
            pattern_description = pattern_description,
            signal_types_text = signal_types_text,
        );

        let config = InferenceConfig::json_structured();
        let messages = vec![ChatMessage::system(system), ChatMessage::user(user)];
        let resp = self
            .client
            .complete_with_config(messages, &config)
            .await
            .with_context(|| "LLM recipe generation failed")?;

        let candidates: Vec<RecipeCandidate> = resp
            .parse_json()
            .with_context(|| "Failed to parse recipe candidates JSON")?;

        // Validate and clamp
        let validated: Vec<RecipeCandidate> = candidates
            .into_iter()
            .map(|mut c| {
                c.confidence_threshold = c.confidence_threshold.clamp(0.5, 0.99);
                c.estimated_base_rate = c.estimated_base_rate.clamp(0.0, 1.0);
                c.expected_precision = c.expected_precision.clamp(0.0, 1.0);
                // Resolve placeholder leaks: replace unreplaced {entity}/{signal}/{region}
                // with neutral prose so stored narratives never show raw placeholders.
                for template in [&mut c.narrative_template, &mut c.action_template] {
                    *template = template
                        .replace("{{entity}}", "the entity")
                        .replace("{{signal}}", "the detected signal")
                        .replace("{{region}}", "the target region")
                        .replace("{entity}", "the entity")
                        .replace("{signal}", "the detected signal")
                        .replace("{region}", "the target region");
                }
                c
            })
            .collect();

        // Dedup by recipe code — LLM may generate duplicates
        let mut seen_codes = std::collections::HashSet::new();
        let deduped: Vec<RecipeCandidate> = validated
            .into_iter()
            .filter(|c| seen_codes.insert(c.code.to_uppercase()))
            .collect();

        Ok(deduped)
    }

    /// Evaluate an existing recipe against its historical performance data.
    pub async fn evaluate_recipe_quality(
        &self,
        recipe_code: &str,
        recipe_name: &str,
        recipe_description: &str,
        precision_history: &[f64],
        false_positive_examples: &[String],
        false_negative_examples: &[String],
    ) -> Result<RecipeEvaluation> {
        let precisions_text = precision_history
            .iter()
            .map(|p| format!("{:.2}", p))
            .collect::<Vec<_>>()
            .join(", ");

        let fp_text = if false_positive_examples.is_empty() {
            "None recorded".into()
        } else {
            false_positive_examples
                .iter()
                .take(5)
                .map(|e| format!("- {}", e))
                .collect::<Vec<_>>()
                .join("\n")
        };

        let fn_text = if false_negative_examples.is_empty() {
            "None recorded".into()
        } else {
            false_negative_examples
                .iter()
                .take(5)
                .map(|e| format!("- {}", e))
                .collect::<Vec<_>>()
                .join("\n")
        };

        let trend = if precision_history.len() >= 2 {
            let recent_avg: f64 = precision_history.iter().rev().take(3).sum::<f64>()
                / 3.0f64.min(precision_history.len() as f64);
            let early_avg: f64 = precision_history.iter().take(3).sum::<f64>()
                / 3.0f64.min(precision_history.len() as f64);
            if recent_avg > early_avg + 0.05 {
                "improving"
            } else if recent_avg < early_avg - 0.05 {
                "degrading"
            } else {
                "stable"
            }
        } else {
            "insufficient_data"
        };

        let system = concat!(
            "You are a data scientist evaluating the quality and health of signal detection recipes ",
            "for an intelligence platform. You make data-driven recommendations about recipe lifecycle ",
            "with a focus on signal-to-noise ratio and actionability.\n/no_think"
        );

        let user = format!(
            r#"Evaluate recipe "{recipe_code}" ({recipe_name}):

DESCRIPTION: {recipe_description}

PRECISION HISTORY (weekly, oldest→newest): {precisions_text}
PRECISION TREND: {trend}

FALSE POSITIVE EXAMPLES:
{fp_text}

FALSE NEGATIVE EXAMPLES:
{fn_text}

Respond ONLY with valid JSON:
{{
  "recipe_code": "{recipe_code}",
  "verdict": "<keep|improve|deprecate|replace>",
  "issues": ["<issue1>"],
  "signal_improvements": ["<improvement1>"],
  "threshold_adjustments": {{"signal_field": <new_threshold>}},
  "improved_narrative": "<updated template or null>",
  "confidence": <0.0-1.0>,
  "reasoning": "<2-3 sentence explanation>"
}}"#,
            recipe_code = recipe_code,
            recipe_name = recipe_name,
            recipe_description = recipe_description,
            precisions_text = precisions_text,
            trend = trend,
            fp_text = fp_text,
            fn_text = fn_text,
        );

        let config = InferenceConfig::json_structured();
        let messages = vec![ChatMessage::system(system), ChatMessage::user(user)];
        let resp = self
            .client
            .complete_with_config(messages, &config)
            .await
            .with_context(|| format!("LLM recipe evaluation failed for {}", recipe_code))?;

        let mut eval: RecipeEvaluation = resp
            .parse_json()
            .with_context(|| "Failed to parse recipe evaluation JSON")?;

        eval.confidence = eval.confidence.clamp(0.0, 1.0);
        Ok(eval)
    }

    /// Analyze false positives for a recipe and suggest filter improvements.
    pub async fn suggest_fp_reductions(
        &self,
        recipe_code: &str,
        current_fpr: f64,
        fp_examples: &[String],
        available_filter_signals: &[String],
    ) -> Result<RecipeImprovementBatch> {
        let fp_text = fp_examples
            .iter()
            .take(10)
            .map(|e| format!("- {}", e))
            .collect::<Vec<_>>()
            .join("\n");

        let filters_text = available_filter_signals.join(", ");
        let fpr_pct = format!("{:.1}%", current_fpr * 100.0);

        let system = concat!(
            "You are an expert at reducing false positive rates in signal detection systems. ",
            "You identify patterns in false positives and suggest precise filter conditions.\n/no_think"
        );

        let user = format!(
            r#"Reduce the false positive rate for recipe "{recipe_code}".

CURRENT FPR: {fpr_pct}
AVAILABLE FILTER SIGNALS: {filters_text}

FALSE POSITIVE EXAMPLES:
{fp_text}

Respond ONLY with valid JSON:
{{
  "recipe_code": "{recipe_code}",
  "current_fpr": {current_fpr},
  "fp_root_cause": "<root cause of false positives>",
  "additional_filter_signals": [
    {{"observation_type": "<type>", "field": "<field>", "operator": "<op>", "threshold": <val or null>}}
  ],
  "threshold_tightening": {{"field_name": <tighter_threshold>}},
  "projected_fpr": <0.0-1.0>,
  "confidence": <0.0-1.0>
}}"#,
            recipe_code = recipe_code,
            current_fpr = current_fpr,
            filters_text = filters_text,
            fp_text = fp_text,
        );

        let config = InferenceConfig::json_structured();
        let messages = vec![ChatMessage::system(system), ChatMessage::user(user)];
        let resp = self
            .client
            .complete_with_config(messages, &config)
            .await
            .with_context(|| format!("LLM FP reduction failed for {}", recipe_code))?;

        let mut batch: RecipeImprovementBatch = resp
            .parse_json()
            .with_context(|| "Failed to parse FP reduction JSON")?;

        batch.projected_fpr = batch.projected_fpr.clamp(0.0, 1.0);
        batch.confidence = batch.confidence.clamp(0.0, 1.0);
        Ok(batch)
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn recipe_candidate_confidence_clamp() {
        let mut candidate = RecipeCandidate {
            code: "TEST".into(),
            name: "Test".into(),
            description: "desc".into(),
            category: "supply_chain".into(),
            severity: "warning".into(),
            regions: vec!["TN".into()],
            signals: vec![],
            confidence_threshold: 1.5, // invalid
            narrative_template: "".into(),
            action_template: "".into(),
            hypothesis_rationale: "".into(),
            estimated_base_rate: -0.1, // invalid
            expected_precision: 2.0,   // invalid
        };
        candidate.confidence_threshold = candidate.confidence_threshold.clamp(0.5, 0.99);
        candidate.estimated_base_rate = candidate.estimated_base_rate.clamp(0.0, 1.0);
        candidate.expected_precision = candidate.expected_precision.clamp(0.0, 1.0);
        assert_eq!(candidate.confidence_threshold, 0.99);
        assert_eq!(candidate.estimated_base_rate, 0.0);
        assert_eq!(candidate.expected_precision, 1.0);
    }
}
