"use client";

import { useQuery } from "@tanstack/react-query";
import {
  PageHeader, SurfaceCard, StatCard, EmptyState, DataTable,
  PAGE_ICONS, Sparkles, Zap, Check
} from "@/components/ui";
import { fetchRecipes } from "@/lib/api";

export default function RecipesPage() {
  const { data: recipesData, isLoading } = useQuery({
    queryKey: ["recipes"],
    queryFn: ({ signal }) => fetchRecipes({ signal, per_page: 100 }),
  });

  const recipes = recipesData?.items ?? [];

  const totalFired = recipes.reduce((sum, r) => sum + r.fired_count, 0);
  const productionCount = recipes.filter((r) => r.status === "Production").length;

  const rows = recipes.map((r) => [
    r.name,
    r.status,
    r.fired_count.toString(),
    `${Math.round(r.precision * 100)}%`,
    r.last_fired ? new Date(r.last_fired).toLocaleDateString() : "–",
  ]);

  return (
    <div>
      <PageHeader
        title="Recipe Manager"
        subtitle="Signal detection recipes and their performance metrics."
        icon={PAGE_ICONS.recipes}
      />

      <div className="grid gap-4 sm:grid-cols-3 mb-6">
        <StatCard label="Active Recipes" value={recipes.length.toString()} icon={<Sparkles className="h-3.5 w-3.5" />} accent="#4A90E2" />
        <StatCard label="Production" value={productionCount.toString()} icon={<Check className="h-3.5 w-3.5" />} accent="#2D8C3C" />
        <StatCard label="Total Alerts" value={totalFired.toLocaleString()} icon={<Zap className="h-3.5 w-3.5" />} accent="#D62D2D" />
      </div>

      <SurfaceCard title="Recipe Signals" icon={<Sparkles className="h-3.5 w-3.5" />}>
        {isLoading ? (
          <p className="text-xs text-muted-foreground animate-pulse">Loading recipes…</p>
        ) : rows.length === 0 ? (
          <EmptyState
            title="No recipes configured"
            description="Signal recipes will appear here once warnings are generated by the system."
          />
        ) : (
          <DataTable headers={["Name", "Status", "Fired", "Precision", "Last Fired"]} rows={rows} />
        )}
      </SurfaceCard>
    </div>
  );
}
