"use client";

import {
  PageHeader, SurfaceCard, StatCard, PriorityBadge, StatusBadge,
  PAGE_ICONS, FileText, Clock, Target, ChevronUp, ChevronDown, Minus
} from "@/components/ui";
import { LATEST_MEMO, PAST_MEMOS } from "@/lib/mock-data";

function DeltaIndicator({ delta, direction }: { delta: string; direction: "up" | "down" | "flat" }) {
  const Icon = direction === "up" ? ChevronUp : direction === "down" ? ChevronDown : Minus;
  const color = direction === "up" ? "text-green-600" : direction === "down" ? "text-red-500" : "text-muted-foreground";
  return (
    <span className={`flex items-center gap-0.5 text-[10px] font-bold ${color}`}>
      <Icon className="h-3 w-3" />
      {delta}
    </span>
  );
}

export default function MemosPage() {
  return (
    <div>
      <PageHeader
        title="Strategy Memos"
        subtitle="Weekly strategy memos for executive review."
        icon={PAGE_ICONS.memos}
      />

      {/* ─── Current Memo Header ─────────────────────────────── */}
      <div className="apex-card p-6 mb-6 border-l-4 border-l-primary">
        <div className="flex items-start justify-between gap-4 mb-4">
          <div>
            <h3 className="text-xl font-black uppercase">{LATEST_MEMO.title}</h3>
            <p className="select-text text-sm text-muted-foreground mt-1">
              Period: {LATEST_MEMO.period} • Published: {new Date(LATEST_MEMO.published).toISOString().slice(0, 10)}
            </p>
            <p className="select-text text-xs text-muted-foreground mt-1">
              Generated by: {LATEST_MEMO.author}
            </p>
          </div>
          <StatusBadge status="Current" variant="success" />
        </div>

        {/* ─── KPI Grid ──────────────────────────────────────── */}
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">
          {LATEST_MEMO.kpis.map((kpi) => (
            <div key={kpi.label} className="rounded-sm border border-border bg-secondary/50 p-3">
              <p className="text-[10px] font-black uppercase tracking-[0.1em] text-muted-foreground">{kpi.label}</p>
              <div className="flex items-end justify-between mt-1">
                <span className="text-lg font-black tabular-nums">{kpi.value}</span>
                <DeltaIndicator delta={kpi.delta} direction={kpi.direction} />
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* ─── Memo Sections ───────────────────────────────────── */}
      <div className="grid gap-4 lg:grid-cols-2 mb-6">
        {LATEST_MEMO.sections.map((section) => (
          <SurfaceCard key={section.heading} title={section.heading} icon={<FileText className="h-3.5 w-3.5" />}>
            <ul className="space-y-2">
              {section.bullets.map((bullet, i) => (
                <li key={i} className="flex items-start gap-2 text-sm">
                  <span className="mt-1.5 h-1.5 w-1.5 rounded-full bg-primary flex-shrink-0" />
                  <span className="select-text text-muted-foreground">{bullet}</span>
                </li>
              ))}
            </ul>
          </SurfaceCard>
        ))}
      </div>

      {/* ─── Priority Actions ────────────────────────────────── */}
      <SurfaceCard title="Priority Actions" icon={<Target className="h-3.5 w-3.5" />}>
        <div className="overflow-x-auto">
          <table className="data-table">
            <thead>
              <tr>
                <th className="w-16">Priority</th>
                <th>Action</th>
                <th className="w-32">Owner</th>
                <th className="w-28">Deadline</th>
              </tr>
            </thead>
            <tbody>
              {LATEST_MEMO.actions.map((action, i) => (
                <tr key={i}>
                  <td><PriorityBadge priority={action.priority} /></td>
                  <td className="text-sm">{action.action}</td>
                  <td className="text-sm text-muted-foreground">{action.owner}</td>
                  <td className="text-sm tabular-nums">{action.deadline}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </SurfaceCard>

      {/* ─── Past Memos ──────────────────────────────────────── */}
      <div className="mt-6">
        <SurfaceCard title="Past Memos" icon={<Clock className="h-3.5 w-3.5" />}>
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            {PAST_MEMOS.map((memo) => (
              <div key={memo.id} className="rounded-sm border border-border bg-secondary/30 p-3 hover:bg-secondary">
                <p className="text-sm font-bold">{memo.title}</p>
                <p className="text-xs text-muted-foreground mt-1">{memo.period}</p>
                <div className="flex items-center gap-3 mt-2 text-[10px] text-muted-foreground">
                  <span>{memo.highlights} highlights</span>
                  <span>•</span>
                  <span>{memo.actions} actions</span>
                </div>
              </div>
            ))}
          </div>
        </SurfaceCard>
      </div>
    </div>
  );
}
